// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AskEp } from '../src/api/ask';
import type { default as _DashboardEp } from '../src/api/dashboard';
import type { default as _ManageDataEp } from '../src/api/manageData';

type _AskCfg = typeof _AskEp;
export type AskInputType = NonNullable<_AskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AskCfg['execute']>[0]['input'];
export type AskOutputType = Awaited<ReturnType<_AskCfg['execute']>>;
export const ask = createCaller<AskInputType, AskOutputType>('ask');

type _DashboardCfg = typeof _DashboardEp;
export type DashboardInputType = NonNullable<_DashboardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DashboardCfg['execute']>[0]['input'];
export type DashboardOutputType = Awaited<ReturnType<_DashboardCfg['execute']>>;
export const dashboard = createCaller<DashboardInputType, DashboardOutputType>('dashboard');

type _ManageDataCfg = typeof _ManageDataEp;
export type ManageDataInputType = NonNullable<_ManageDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ManageDataCfg['execute']>[0]['input'];
export type ManageDataOutputType = Awaited<ReturnType<_ManageDataCfg['execute']>>;
export const manageData = createCaller<ManageDataInputType, ManageDataOutputType>('manageData');


export const api = {
  ask,
  dashboard,
  manageData,
};
