// Generated by Zite. Do not edit.
declare namespace NodeJS {
  interface ProcessEnv {
    /** Public URL of the current app. */
    ZITE_APP_URL: string;
    /** gemini access token (gemini) */
    ZITE_GEMINI_ACCESS_TOKEN: string;
    [key: string]: string | undefined;
  }
}
